### ISSUE TITLE
Add Velocity support

### ISSUE THREAD

**Issue by BingYanchi** [DavideBlade/AntiWorldDownloader#4]
Add Velocity support

**Comment by DavideBlade** [comment]
Unfortunately, to add support for Velocity it is necessary to remove support for other versions of Minecraft (e.g. 1.8) due to the required Java version so I have to consider when and if to do this. Also, to add Velocity it is necessary to restructure the plugin using Maven so it will require time anyway.

**Comment by WitchBoo** [comment]
> Unfortunately, to add support for Velocity it is necessary to remove support for other versions of Minecraft (e.g. 1.8) due to the required Java version so I have to consider when and if to do this. Also, to add Velocity it is necessary to restructure the plugin using Maven so it will require time anyway.

Can I restructure and add support for you?

**Comment by WitchBoo** [comment]
> Unfortunately, to add support for Velocity it is necessary to remove support for other versions of Minecraft (e.g. 1.8) due to the required Java version so I have to consider when and if to do this. Also, to add Velocity it is necessary to restructure the plugin using Maven so it will require time anyway.

I can do it if you want

**Comment by DavideBlade** [comment]
> I can do it if you want

If you feel like it, for the Maven part you can send a pull request with the changes. If you want, you can already structure it so that it can also support other forks of Spigot (at the moment precisely the support is only for original BungeeCord and Spigot).

Please note: I am quite critical about the code, it should not be sloppy and no warnings or errors should be generated when compiling with Maven.

**Comment by DavideBlade** [comment]
[diamondblocks](https://www.spigotmc.org/members/diamondblocks.379784/) [requested](https://www.spigotmc.org/threads/antiworlddownloader.543358/#post-4700157) Velocity support too.

**Comment by DavideBlade** [comment]
@WitchBoo @BingYanchi
Feature added in version [2.6.7](https://github.com/DavideBlade/AntiWorldDownloader/commit/36c0ff5d71c008bbd8cba774f3893e2aff4985db) (b7f6c3be890871604655ed8db1d5410a32c489d5). Thanks for the suggestion!
